//! This code was generated by `zbus-xmlgen` `3.0.0` from DBus introspection data.


use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "ludo_ic.daemon.producer",
    default_service = "ludo_ic.daemon.producer",
    default_path = "/ludo_ic/daemon/producer",
    async_name = "ProducerProxyAsync",
    blocking_name = "ProducerProxyBlocking"
)]
trait Producer {
    /// MySignalEvent signal
    #[dbus_proxy(signal)]
    fn my_signal_event(&self, val1: i32, val2: i32) -> zbus::Result<()>;
}
